version = 0.1

[default.deploy.parameters]
stack_name = "staging-todolist-aws"
resolve_s3 = true
s3_prefix = "staging-todolist-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"staging\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
